name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@d09bd5e6005b175076f227b13d9730d56e9dcfcb # v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pipenv
          pipenv install --python "3.10" --dev --system --deploy
      - name: Lint with Mypy
        run: mypy ballcone tools
      - name: Lint with flake8
        run: flake8
      - name: Test with unittest
        run: python3 -m unittest discover
      - name: Build
        run: python3 -m build --sdist --wheel .
      - name: Build with PyInstaller
        run: |
          pyinstaller ballcone.spec
          dist/ballcone --version
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Update Docker Hub description
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: dustalov/ballcone
          short-description: ${{ github.event.repository.description }}
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Ballcone
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            dustalov/ballcone:latest
            ghcr.io/dustalov/ballcone:latest
      - name: Build and push Ballcone Demo
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5
        with:
          context: .
          file: Dockerfile.demo
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            dustalov/ballcone:demo
            ghcr.io/dustalov/ballcone:demo
